server:
  port: 8090
  tomcat:
    max-http-post-size: 1024000000
  servlet:
    context-path: /wang
  error:
    path: /wang/error


#跨域支持
web.cors:
  enabled: true
  allowCredentials: true
  allowedOrigins:
    - '*'
  allowedHeaders:
    - '*'
  allowedMethods:
    - '*'