server:
  port: 8089
  tomcat:
    max-http-post-size: 1024000000
  servlet:
    context-path: /wang
  error:
    path: /wang/error

spring:
  datasource:
#    url: jdbc:log4jdbc:mysql://localhost:3306/wang?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    url: jdbc:mysql://localhost:3306/wang?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
