spring:
  datasource:
#    url: jdbc:log4jdbc:mysql://localhost:3306/wang?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    url: jdbc:mysql://localhost:3306/wang?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  kafka:
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: 172.16.239.7:9092
    consumer:
      bootstrap-servers: 172.16.239.7:9092
      group-id: test_dev
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      topic-1: test_test

  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: localhost:9300
      cluster-name: elasticsearch
      properties:
        transport:
          tcp:
            connect_timeout: 120s